### ISSUE TITLE
Comparison between genotypes

### ISSUE THREAD

**Issue by mverocai** [Illustratien/toolStability#6]
Hello! Great package!
Maybe it is not the right place but I have a question.
Is it right to compare genotypes that appear different times in the data? or the genotypes must be balanced? I have some genotypes that are missing in some experiments, and maybe the result for a given function,  Genotypic superiority measure for example, of those genotypes that appear in more experiments might be inflated.
Thanks

**Comment by Illustratien** [comment]
Hello,
Thanks for the question.
Unfortunately there is no argument in the function yet.
But you can consider to split your data by replication and conduct the analysis for each replicates and combine all of them together.
```
library(dplyr)
library(magrittr)
 data%>%
 group_by(rep)%>%
 group_split()%>%
 purrr::map_dfr(.,~{
toolStability::fun(data = .x,genotype = 'genotype_columnname',environment = 'environment_columnname')
 })

```
